#!/bin/bash
# SGLang model preset for Qwen3-235B-A22B.

MODEL="${MODEL:-Qwen/Qwen3-235B-A22B}"
MODEL_NAME="${MODEL_NAME:-qwen3-235b-a22b}"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-31877}"

TP="${TP:-8}"
DP="${DP:-1}"

WARMUPS="${WARMUPS:-3}"
MAX_RUNNING_REQUESTS="${MAX_RUNNING_REQUESTS:-2}"
CHUNKED_PREFILL_SIZE="${CHUNKED_PREFILL_SIZE:-8192}"

TOOL_CALL_PARSER="${TOOL_CALL_PARSER:-qwen}"
CONTEXT_LENGTH="${CONTEXT_LENGTH:-32768}"
MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.90}"
LOG_LEVEL="${LOG_LEVEL:-info}"

ENABLE_FLASHINFER="${ENABLE_FLASHINFER:-true}"
ENABLE_DP_ATTENTION="${ENABLE_DP_ATTENTION:-false}"

LOG_DIR="${LOG_DIR:-}"
CACHE_DIR="${CACHE_DIR:-}"
