#!/bin/bash
# SGLang model preset for Qwen3-4B-Instruct-2507.

MODEL="${MODEL:-/work/projects/polyullm/yuhang/post-train/models/Qwen/Qwen3-4B-Instruct-2507}"
MODEL_NAME="${MODEL_NAME:-qwen3-4b-instruct-2507}"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-31877}"

TP="${TP:-8}"
DP="${DP:-8}"

WARMUPS="${WARMUPS:-3}"
MAX_RUNNING_REQUESTS="${MAX_RUNNING_REQUESTS:-16}"
CHUNKED_PREFILL_SIZE="${CHUNKED_PREFILL_SIZE:-32768}"

TOOL_CALL_PARSER="${TOOL_CALL_PARSER:-qwen}"
CONTEXT_LENGTH="${CONTEXT_LENGTH:-8192}"
MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.95}"
LOG_LEVEL="${LOG_LEVEL:-info}"

ENABLE_FLASHINFER="${ENABLE_FLASHINFER:-true}"
ENABLE_DP_ATTENTION="${ENABLE_DP_ATTENTION:-true}"

LOG_DIR="${LOG_DIR:-}"
CACHE_DIR="${CACHE_DIR:-}"
